# Generated by Django 5.2.3 on 2025-07-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
