# Generated by Django 5.2.3 on 2025-07-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_spaces_alter_reaction_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='spaces',
        ),
    ]
